# Generated by Django 5.1.2 on 2025-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_delete_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='paloma', max_length=200),
            preserve_default=False,
        ),
    ]
