# Generated by Django 5.1.2 on 2025-05-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
